"""Add profile fields to User model

Revision ID: b7014d1fe97d
Revises: 58e0f0d03d1a
Create Date: 2025-09-12 21:58:36.690746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7014d1fe97d'
down_revision = '58e0f0d03d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_picture', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('school_college', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'school_college')
    op.drop_column('user', 'dob')
    op.drop_column('user', 'profile_picture')
    # ### end Alembic commands ###
